name: .NET Core

on: [push, pull_request]

jobs:
  build:
    name: Build on dotnet using ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Build with dotnet
        run: dotnet build --framework=netcoreapp3.1 -c Release